add layout for component page and media queries
js-tasks-ru/htmlcss-20220210_natalya59 pull request #14
Opened 2022-03-10 18:36 UTC by nvknkhv

2022-03-10 18:37 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-03-10 21:11 UTC, GSemikozov requested changes

2022-03-10 21:11 UTC, GSemikozov commented on components/container/container.css
> +@media (max-width: 376px) {
для контейнера весь этот медиа-запрос будет лишним - можно просто сразу добавить padding: 0 15px; box-sizing: border-box )

2022-03-11 06:20 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-03-11 06:25 UTC, nvknkhv commented on components/container/container.css
> +@media (max-width: 376px) {
поправила, спасибо!)

2022-03-11 06:25 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-03-11 06:29 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-03-11 06:32 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-03-15 20:51 UTC, GSemikozov approved these changes

2022-03-15 20:51 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2022-03-15 20:52 UTC, GSemikozov approved these changes

2022-03-15 20:52 UTC, merged