add 03-lection1-button
js-tasks-ru/htmlcss-20220210_natalya59 pull request #3
Opened 2022-02-19 11:57 UTC by nvknkhv

2022-02-19 11:58 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-02-19 20:54 UTC, GSemikozov requested changes

2022-02-19 20:54 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    cursor: pointer;
здесь же можно добавить паддинги и стили для оформления текста

2022-02-19 20:54 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button, .button_primary {
просто .button_primary

и везде ниже тоже поправить

2022-02-19 20:54 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button, .button_primary {
дублировать .button не надо

2022-03-03 16:19 UTC, GSemikozov approved these changes

2022-03-03 16:19 UTC, merged