add 04-lection2-skeleton
js-tasks-ru/htmlcss-20220210_natalya59 pull request #6
Opened 2022-02-21 05:53 UTC by nvknkhv

2022-02-21 05:54 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-02-21 05:54 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-02-22 16:39 UTC, GSemikozov requested changes

2022-02-22 16:39 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    width: 579px;
жестко не фиксируем

2022-02-22 16:39 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.wrapper {
.skeleton__content?

2022-02-22 16:39 UTC, GSemikozov commented on 04-lection2/02-skeleton/index.html
> +                    <div class="skeleton__rectangle" style="width: 172px"></div>
а вот здесь все-таки лучше модификаторы - у нас всего 3 разных по размеру линии)

2022-03-03 16:22 UTC, GSemikozov requested changes

2022-03-03 16:22 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__rectangle-width-half {
.skeleton__rectangle-width-half -> .skeleton__rectangle_width-half

2022-03-03 16:22 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__rectangle-width-third {
.skeleton__rectangle_width-third

2022-03-03 18:20 UTC, nvknkhv commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__rectangle-width-half {
поправила, спасибо!

2022-03-03 18:21 UTC, nvknkhv commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__rectangle-width-third {
поправила, спасибо!

2022-03-10 21:12 UTC, GSemikozov approved these changes

2022-03-10 21:12 UTC, merged